### ISSUE TITLE
Take into account the Chromium's never-sniff MIME types

### ISSUE THREAD

**Issue by annevk** [annevk/orb#10]
@anforowicz in #8 you shared https://source.chromium.org/chromium/chromium/src/+/master:services/network/public/cpp/cross_origin_read_blocking.cc;l=251;drc=a122d0fda4ecbcf6fd184a5393be1d13b867a868. Could this basically be a list we have near the top of the algorithm and return false early for or is there also sniffing involved?

**Comment by anforowicz** [comment]
Correct - this would be a list at the top (in the we-extracted-the-MIME-type-successfully part) that can just return false (i.e. blocked) early.
