### ISSUE TITLE
JSON vs Javascript lists

### ISSUE THREAD

**Issue by anforowicz** [annevk/orb#2]
What is your plan for handling scenarios where the first 1024 bytes look like a beginning of list?

    [ 1, 2, 3, "1024 bytes like that", ....

Such a prefix can be extended to form valid JSON and invalid Javascript:

    [ 1, 2, 3, "foobar" ]

or it can be extended to form valid Javascript and invalid JSON:

    [ 1, 2, 3, "foobar" ].map(x => console.log(x))

I assume that step 14 works with the first 1024 bytes (otherwise we increase further the latency of making the first bytes available in the renderer process).  OTOH, step 14 says "response's body" rather than "bytes", so maybe this is a wrong assumption.

PS. Is there a Mozilla bug we can follow to see if the proposed algorithm works well in practice?  If Javascript sniffing turns out to be robust against real websites, then the proposed algorithm seems like an important improvement in coverage of CORB.

**Comment by annevk** [comment]
Ah, I guess I should add another step before step 14 that waits for the complete response. Defining a parser for partial input seemed rather involved, error-prone, and hard to standardize. Also, it might not necessarily be that bad as depending on your architecture you could perhaps transfer the output of the parser across the process boundary. But also, the slight performance hit should give sites even more reason to migrate to using the correct MIME type and such.

https://bugzilla.mozilla.org/show_bug.cgi?id=1532642 tracks this, but it's not a priority currently.
