### ISSUE TITLE
Consider explicitly handling "application/dash+xml" MIME type

### ISSUE THREAD

**Issue by anforowicz** [annevk/orb#20]
Should we explicitly add "application/dash+xml" to the definition of "an opaque-safelisted MIME type"?

Based on [the docs for DASH Adaptive Streaming](https://developer.mozilla.org/en-US/docs/Web/Media/DASH_Adaptive_Streaming_for_HTML_5_Video#using_dash_-_client_side), it seems that this MIME type may be directly used in video tags.  CORB had to start explicitly recognizing this MIME type in https://crbug.com/947498.

FWIW, I see that https://mimesniff.spec.whatwg.org/#audio-or-video-mime-type 1) doesn't list "application/dash+xml" and 2) also lists "application/ogg" (but this one should be covered by ORB's reference to the [audio/video sniffing](https://mimesniff.spec.whatwg.org/#audio-or-video-type-pattern-matching-algorithm))

**Comment by anforowicz** [comment]
(I think that currently [without the proposed changes] the ORB algorithm would block "application/dash+xml" responses in the final step, because earlier steps would decide that the response doesn't sniff as video and doesn't sniff as JavaScript.)

**Comment by annevk** [comment]
Yeah that seems reasonable. (See also https://github.com/whatwg/fetch/issues/886.)

Are there web-platform-tests for this?

**Comment by annevk** [comment]
Do we need to keep this open now that we have #29?

**Comment by anforowicz** [comment]
You're right - it's probably best to just keep track this in #29
